wandb_version: 1

metric_to_optimize:
  desc: null
  value: accuracy
_wandb:
  desc: null
  value:
    python_version: 3.11.0rc1
    cli_version: 0.16.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705926650.730626
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.11.0rc1
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
